<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126072256 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_name VARCHAR(50) NOT NULL, provider_content_id VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, content_type VARCHAR(255) NOT NULL, score DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_content_type ON content (content_type)');
        $this->addSql('CREATE UNIQUE INDEX unique_provider_content ON content (provider_name, provider_content_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX unique_provider_content');
        $this->addSql('DROP INDEX idx_content_type');
        $this->addSql('DROP TABLE content');
    }
}
